services:
  - type: worker
    name: redhat-bot-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_tracker.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_CLIENT_X509_URL
        sync: false
